"""widen source_url column

Revision ID: a07c418f814d
Revises: ccec52b50284
Create Date: 2026-06-22 00:51:48.169480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a07c418f814d'
down_revision: Union[str, Sequence[str], None] = 'ccec52b50284'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('incidents', 'reported_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('incidents', 'source_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('incidents', 'source_url',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('incidents', 'reported_by',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
