"""add source columns to incidents

Revision ID: ccec52b50284
Revises: d1f3a2a8f68b
Create Date: 2026-06-22 00:02:35.665603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccec52b50284'
down_revision: Union[str, Sequence[str], None] = 'd1f3a2a8f68b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('source', sa.Enum('user_report', 'news_scraper', name='incidentsource'), nullable=False, server_default='user_report'))
    op.add_column('incidents', sa.Column('source_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'source_url')
    op.drop_column('incidents', 'source')
    # ### end Alembic commands ###
